### ISSUE TITLE
Add Github action

### ISSUE THREAD

**Issue by cadars** [cadars/portable-php#2]
I tried to add a simple Github action to run `portable.php` from the repo:

```yml
name: RUN
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nanasess/setup-php@master
      with:
        php-version: '5.6'
    - run: php ./portable.php > index.html
```

But it produced these errors:

<img width="1001" alt="Screen Shot 2021-10-20 at 06 08 47" src="https://user-images.githubusercontent.com/467112/148099289-87a0f999-afcd-49c8-869e-9723d77ce676.png">

Anyone with some PHP skills to point me in the right direction?
